# Importando a base de dados

In [1]:
import pandas as pd
import numpy as np

In [9]:
dt = pd.read_csv("Curso de Estatística/dados.csv", sep=",")
dt

UF  Sexo  Idade  Cor  Anos de Estudo  Renda    Altura
0      11     0     23    8              12    800  1.603808
1      11     1     23    2              12   1150  1.739790
2      11     1     35    8              15    880  1.760444
3      11     0     46    2               6   3500  1.783158
4      11     1     47    8               9    150  1.690631
...    ..   ...    ...  ...             ...    ...       ...
76835  53     1     46    2              11    812  1.687030
76836  53     0     30    4               7   1500  1.792934
76837  53     0     32    8              12   1300  1.830587
76838  53     0     57    8               4   1500  1.726344
76839  53     0     38    8               4    900  1.658305

[76840 rows x 7 columns]

# Pré análise dos dados

In [12]:
type(dt)

pandas.core.frame.DataFrame

### Dados estatísticos

In [13]:
dt.describe()

UF          Sexo         Idade           Cor  Anos de Estudo  \
count  76840.000000  76840.000000  76840.000000  76840.000000    76840.000000   
mean      31.912962      0.307002     44.071421      5.032613        9.469664   
std       11.147830      0.461253     12.480583      2.857118        4.539929   
min       11.000000      0.000000     13.000000      0.000000        1.000000   
25%       25.000000      0.000000     34.000000      2.000000        6.000000   
50%       31.000000      0.000000     43.000000      4.000000       11.000000   
75%       41.000000      1.000000     53.000000      8.000000       12.000000   
max       53.000000      1.000000     99.000000      8.000000       17.000000   

               Renda        Altura  
count   76840.000000  76840.000000  
mean     2000.383199      1.699512  
std      3323.387730      0.079717  
min         0.000000      1.339245  
25%       788.000000      1.645785  
50%      1200.000000      1.699325  
75%      2000.000000      1.753062  
max    200000.000000      2.028497

### Informações do dt

In [14]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76840 entries, 0 to 76839
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   UF              76840 non-null  int64  
 1   Sexo            76840 non-null  int64  
 2   Idade           76840 non-null  int64  
 3   Cor             76840 non-null  int64  
 4   Anos de Estudo  76840 non-null  int64  
 5   Renda           76840 non-null  int64  
 6   Altura          76840 non-null  float64
dtypes: float64(1), int64(6)
memory usage: 4.1 MB


# Variáveis qualitativas

São aquelas cujos valores podem ser separados em diferentes categorias que se distinguem por alguma característica não numérica. Ex.: Masculino e feminino, cor do cabelo, cor da pele

## Variáveis qualitativas ordinais

São variáveis que podem ser ordenadas/hierarquizadas. Grau de instrução, faixa de idades, patentes e etc.

In [16]:
dt.head()

UF  Sexo  Idade  Cor  Anos de Estudo  Renda    Altura
0  11     0     23    8              12    800  1.603808
1  11     1     23    2              12   1150  1.739790
2  11     1     35    8              15    880  1.760444
3  11     0     46    2               6   3500  1.783158
4  11     1     47    8               9    150  1.690631

In [18]:
sorted(dt['Anos de Estudo'].unique())

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

As variáveis(features) "Anos de Estudo", "Renda" e "Altura" podem ser classificadas como variáveis qualitativas ordinais.

## Variáveis qualitativas nominais

Quando uma ordem não pode ser estabelecida nos seus valores ou quando essa ordem não importa no resultado final.

In [26]:
dt.head()

UF  Sexo  Idade  Cor  Anos de Estudo  Renda    Altura
0  11     0     23    8              12    800  1.603808
1  11     1     23    2              12   1150  1.739790
2  11     1     35    8              15    880  1.760444
3  11     0     46    2               6   3500  1.783158
4  11     1     47    8               9    150  1.690631

As variáveis UF, Sexo e Cor são classificadas como variáveis nominais.

In [28]:
dt.UF.unique()

array([11, 12, 13, 14, 15, 16, 17, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31,
       32, 33, 35, 41, 42, 43, 50, 51, 52, 53], dtype=int64)

In [31]:
dt.Sexo.unique()

array([0, 1], dtype=int64)

In [32]:
dt.Cor.unique()

array([8, 2, 4, 6, 0], dtype=int64)

# Variáveis quantitativas

São aquelas variáveis expressas por meio de números

## Variáveis quantitativas discretas

Quando resultam num conjunto finito(enumerável) de valores possíveis (números inteiros). Qnt de livros de uma biblioteca, qnt de carros em um estatcionamento são exemplos de variáveis quantitativas discretas


In [33]:
dt.Idade.unique()

array([23, 35, 46, 47, 34, 57, 60, 50, 26, 49, 52, 38, 45, 43, 53, 62, 69,
       41, 25, 33, 44, 65, 32, 30, 64, 31, 63, 40, 28, 37, 39, 36, 73, 56,
       27, 42, 51, 29, 24, 55, 67, 66, 61, 54, 48, 80, 79, 71, 59, 19, 22,
       77, 58, 17, 72, 70, 18, 21, 20, 68, 74, 76, 75, 84, 85, 78, 15, 82,
       95, 13, 83, 81, 87, 88, 16, 91, 92, 97, 89, 90, 86, 94, 14, 99],
      dtype=int64)

In [34]:
dt.Renda.unique()

array([  800,  1150,   880, ..., 36000,  1329,  5260], dtype=int64)

In [35]:
print("Menor idade: ", dt.Idade.min())
print("Maior idade: ", dt.Idade.max())

Menor idade:  13
Maior idade:  99


In [37]:
print("Menor renda: ", dt.Renda.min())
print("Maior renda: ", dt.Renda.max())

Menor renda:  0
Maior renda:  200000


## Variável quantitativa contínua

Quando resulta de um número infinito de valores possíveis, resultando de uma escala contínua, de modo que não haja lacunas ou interrupções entre os valores. Altura, peso, largura, comprimento, temperatura, horas e idade são exemplos de variáveis contínuas

In [38]:
dt.head()

UF  Sexo  Idade  Cor  Anos de Estudo  Renda    Altura
0  11     0     23    8              12    800  1.603808
1  11     1     23    2              12   1150  1.739790
2  11     1     35    8              15    880  1.760444
3  11     0     46    2               6   3500  1.783158
4  11     1     47    8               9    150  1.690631

In [39]:
dt.Altura.unique()

array([1.60380762, 1.73978983, 1.76044382, ..., 1.83058738, 1.72634426,
       1.65830485])

In [43]:
print("Menor altura: ", dt.Altura.min(), ", Maior Altura: ", dt.Altura.max())

Menor altura:  1.339244614 , Maior Altura:  2.028496765
